services:
  # ── Next.js Web Frontend ────────────────────────────────────────────────
  - type: web
    name: social-web
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npx turbo run start --filter=web
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
      - key: NEST_API_URL
        value: "https://social-api-azcv.onrender.com/api"
      - key: NEXT_PUBLIC_API_URL
        value: "https://social-api-azcv.onrender.com/api"

  # ── NestJS API Server (Handles API & Background Queue Workers Internally!) ─
  - type: web
    name: social-api
    env: node
    plan: free
    buildCommand: npm install && npm run build && npx prisma db push --schema=packages/database/prisma/schema.prisma
    startCommand: npx turbo run start:prod --filter=api
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
      - key: PORT
        value: 3001
      - key: FRONTEND_URL
        value: "https://social-web-azcv.onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: social-db
          property: connectionString
      - key: REDIS_URL
        sync: false
        placeholder: "redis://default:your-password@your-upstash-redis.upstash.io:6379"
      - key: JWT_SECRET
        generateValue: true

databases:
  - name: social-db
    plan: free
